### ISSUE TITLE
Add support for Google Cloud Storage

### ISSUE THREAD

**Issue by nightfury1204** [kubevault/operator#60]
- [x]  test https://github.com/jetstack/vault-unsealer  for google and aws
- [x]  Keep Vault data store and keys are in different path
- [ ]  Vault operator cli to ease the process to setup google storage as backend

**Comment by nightfury1204** [comment]
# Keep Vault data store and keys are in different path
In GCS, we can't define path to store data in vault
But, vault write secrets data in logical/ directory

**Comment by nightfury1204** [comment]
In google,
- jetstack/vault-unsealer used bucket to store keys
In aws
- jetstack/vault-unsealer used system manager parameter store to store keys

**Comment by tamalsaha** [comment]
This issue was moved to kubevault/i2#3
